language: node_js
node_js:
    - 13

services:
    - docker

install:
    - docker build -t dns-propagation-checker .
    #- docker run -it -p 3000:3000 dns-propagation-checker

after_install:
    - docker rm -f dns-propagation-checker
    - docker images -q | xargs docker rmi -f
